# Generated by Django 6.0.1 on 2026-03-31 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(default=30)),
                (
                    "sex",
                    models.IntegerField(
                        choices=[(1, "Male"), (0, "Female")], default=1
                    ),
                ),
                ("cholesterol", models.IntegerField(default=200)),
                ("systolic_bp", models.IntegerField(default=120)),
                ("diastolic_bp", models.IntegerField(default=80)),
                ("diabetes", models.BooleanField(default=False)),
                ("smoking", models.BooleanField(default=False)),
                ("obesity", models.BooleanField(default=False)),
                ("alcohol_consumption", models.BooleanField(default=False)),
                ("previous_heart_problems", models.BooleanField(default=False)),
                ("medication_use", models.BooleanField(default=False)),
                ("triglycerides", models.IntegerField(default=150)),
                ("bmi", models.FloatField(default=22.0)),
                (
                    "diet",
                    models.IntegerField(
                        choices=[(0, "Unhealthy"), (1, "Average"), (2, "Healthy")],
                        default=1,
                    ),
                ),
                ("exercise_hours_per_week", models.FloatField(default=5.0)),
                ("stress_level", models.IntegerField(default=5)),
                ("sedentary_hours_per_day", models.FloatField(default=8.0)),
                ("physical_activity_days_per_week", models.IntegerField(default=3)),
                ("sleep_hours_per_day", models.IntegerField(default=7)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
