# Generated by Django 6.0.3 on 2026-04-02 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="last_sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("reset_password", "Reset Password"),
                ],
                default="register",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="emailotp",
            unique_together={("email", "purpose")},
        ),
    ]
