# Generated by Django 6.0.1 on 2026-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailotp_last_sent_at_emailotp_purpose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location_permission_granted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_permission_granted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="code",
            field=models.CharField(max_length=5),
        ),
    ]
