# Generated by Django 6.0.1 on 2026-04-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile_location_permission_granted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="critical_alert_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_critical_message_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
