# Generated by Django 6.0.1 on 2026-04-03 10:51

from django.db import migrations, models


def assign_unique_contact_priorities(apps, schema_editor):
    EmergencyContact = apps.get_model("health", "EmergencyContact")

    user_ids = (
        EmergencyContact.objects.order_by()
        .values_list("user_id", flat=True)
        .distinct()
    )

    for user_id in user_ids:
        contacts = EmergencyContact.objects.filter(user_id=user_id).order_by("id")
        for priority, contact in enumerate(contacts, start=1):
            contact.priority = priority
            contact.save(update_fields=["priority"])


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emergencycontact",
            options={"ordering": ("priority", "id")},
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="priority",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(assign_unique_contact_priorities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="emergencycontact",
            constraint=models.UniqueConstraint(
                fields=("user", "priority"),
                name="unique_emergency_contact_priority_per_user",
            ),
        ),
    ]
